#ifndef PROCESS_MGMT_H
#define PROCESS_MGMT_H

#define MAX_PROCESSES 100

typedef enum {
    STATE_NONE,
    STATE_SUBMITTED, // Code parsed & ASM generated
    STATE_RUNNING,   // Currently executing in VM
    STATE_PAUSED,
    STATE_TERMINATED,
    STATE_FAILED
} ProcessStatus;

typedef struct {
    int pid;                // Unique Program ID
    char input_file[256];   // Original source (.lang)
    char output_file[256];  // Generated assembly (.asm)
    char bytecode_file[256]; // Generated bytecode (.byc)    
    ProcessStatus status;   // Current state
    int exit_code;          // Exit code
} Process;

// Global process table
extern Process process_table[MAX_PROCESSES];
extern int next_pid;

// Function prototypes
void init_process_table();
int create_process(char *input_filename);
Process* get_process(int pid);
void update_process_state(int pid, ProcessStatus new_state);
void print_process_list();
void delete_process(int pid);
int handle_ps(char **args);
int handle_submit(char **args);
int handle_run(char **args);
int handle_kill(char **args);
void debug_program(int pid);
int handle_debug(char **args, int arg_count) ;

#endif